//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace alenen
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class alenenDBEntities : DbContext
    {
        public alenenDBEntities()
            : base("name=alenenDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AnaKategori> AnaKategoris { get; set; }
        public virtual DbSet<Begeni> Begenis { get; set; }
        public virtual DbSet<Cinsiyet> Cinsiyets { get; set; }
        public virtual DbSet<Kategori> Kategoris { get; set; }
        public virtual DbSet<Konular> Konulars { get; set; }
        public virtual DbSet<UserActivation> UserActivations { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<Yorum> Yorums { get; set; }
    
        public virtual ObjectResult<Nullable<int>> DeleteUser(Nullable<int> userid)
        {
            var useridParameter = userid.HasValue ?
                new ObjectParameter("userid", userid) :
                new ObjectParameter("userid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("DeleteUser", useridParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> Insert_Usera(string kadi, string sifre, string mail, Nullable<System.DateTime> olusumtarih, Nullable<bool> aktifmi, Nullable<bool> adminmi, string resim, Nullable<bool> sozlesme, string isim, string soyisim, string telefon, Nullable<int> cinsiyetid, Nullable<bool> moderatormu, string resetPasswordCode)
        {
            var kadiParameter = kadi != null ?
                new ObjectParameter("kadi", kadi) :
                new ObjectParameter("kadi", typeof(string));
    
            var sifreParameter = sifre != null ?
                new ObjectParameter("sifre", sifre) :
                new ObjectParameter("sifre", typeof(string));
    
            var mailParameter = mail != null ?
                new ObjectParameter("mail", mail) :
                new ObjectParameter("mail", typeof(string));
    
            var olusumtarihParameter = olusumtarih.HasValue ?
                new ObjectParameter("olusumtarih", olusumtarih) :
                new ObjectParameter("olusumtarih", typeof(System.DateTime));
    
            var aktifmiParameter = aktifmi.HasValue ?
                new ObjectParameter("aktifmi", aktifmi) :
                new ObjectParameter("aktifmi", typeof(bool));
    
            var adminmiParameter = adminmi.HasValue ?
                new ObjectParameter("adminmi", adminmi) :
                new ObjectParameter("adminmi", typeof(bool));
    
            var resimParameter = resim != null ?
                new ObjectParameter("resim", resim) :
                new ObjectParameter("resim", typeof(string));
    
            var sozlesmeParameter = sozlesme.HasValue ?
                new ObjectParameter("sozlesme", sozlesme) :
                new ObjectParameter("sozlesme", typeof(bool));
    
            var isimParameter = isim != null ?
                new ObjectParameter("isim", isim) :
                new ObjectParameter("isim", typeof(string));
    
            var soyisimParameter = soyisim != null ?
                new ObjectParameter("soyisim", soyisim) :
                new ObjectParameter("soyisim", typeof(string));
    
            var telefonParameter = telefon != null ?
                new ObjectParameter("telefon", telefon) :
                new ObjectParameter("telefon", typeof(string));
    
            var cinsiyetidParameter = cinsiyetid.HasValue ?
                new ObjectParameter("cinsiyetid", cinsiyetid) :
                new ObjectParameter("cinsiyetid", typeof(int));
    
            var moderatormuParameter = moderatormu.HasValue ?
                new ObjectParameter("moderatormu", moderatormu) :
                new ObjectParameter("moderatormu", typeof(bool));
    
            var resetPasswordCodeParameter = resetPasswordCode != null ?
                new ObjectParameter("ResetPasswordCode", resetPasswordCode) :
                new ObjectParameter("ResetPasswordCode", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("Insert_Usera", kadiParameter, sifreParameter, mailParameter, olusumtarihParameter, aktifmiParameter, adminmiParameter, resimParameter, sozlesmeParameter, isimParameter, soyisimParameter, telefonParameter, cinsiyetidParameter, moderatormuParameter, resetPasswordCodeParameter);
        }
    
        public virtual int UpdateUser(Nullable<int> userid, string kadi, string sifre, string mail, Nullable<System.DateTime> olusumtarih, Nullable<bool> aktifmi, Nullable<bool> adminmi, string resim, Nullable<bool> sozlesme, string isim, string soyisim, string telefon, Nullable<int> cinsiyetid, Nullable<bool> moderatormu, string resetPasswordCode)
        {
            var useridParameter = userid.HasValue ?
                new ObjectParameter("userid", userid) :
                new ObjectParameter("userid", typeof(int));
    
            var kadiParameter = kadi != null ?
                new ObjectParameter("kadi", kadi) :
                new ObjectParameter("kadi", typeof(string));
    
            var sifreParameter = sifre != null ?
                new ObjectParameter("sifre", sifre) :
                new ObjectParameter("sifre", typeof(string));
    
            var mailParameter = mail != null ?
                new ObjectParameter("mail", mail) :
                new ObjectParameter("mail", typeof(string));
    
            var olusumtarihParameter = olusumtarih.HasValue ?
                new ObjectParameter("olusumtarih", olusumtarih) :
                new ObjectParameter("olusumtarih", typeof(System.DateTime));
    
            var aktifmiParameter = aktifmi.HasValue ?
                new ObjectParameter("aktifmi", aktifmi) :
                new ObjectParameter("aktifmi", typeof(bool));
    
            var adminmiParameter = adminmi.HasValue ?
                new ObjectParameter("adminmi", adminmi) :
                new ObjectParameter("adminmi", typeof(bool));
    
            var resimParameter = resim != null ?
                new ObjectParameter("resim", resim) :
                new ObjectParameter("resim", typeof(string));
    
            var sozlesmeParameter = sozlesme.HasValue ?
                new ObjectParameter("sozlesme", sozlesme) :
                new ObjectParameter("sozlesme", typeof(bool));
    
            var isimParameter = isim != null ?
                new ObjectParameter("isim", isim) :
                new ObjectParameter("isim", typeof(string));
    
            var soyisimParameter = soyisim != null ?
                new ObjectParameter("soyisim", soyisim) :
                new ObjectParameter("soyisim", typeof(string));
    
            var telefonParameter = telefon != null ?
                new ObjectParameter("telefon", telefon) :
                new ObjectParameter("telefon", typeof(string));
    
            var cinsiyetidParameter = cinsiyetid.HasValue ?
                new ObjectParameter("cinsiyetid", cinsiyetid) :
                new ObjectParameter("cinsiyetid", typeof(int));
    
            var moderatormuParameter = moderatormu.HasValue ?
                new ObjectParameter("moderatormu", moderatormu) :
                new ObjectParameter("moderatormu", typeof(bool));
    
            var resetPasswordCodeParameter = resetPasswordCode != null ?
                new ObjectParameter("ResetPasswordCode", resetPasswordCode) :
                new ObjectParameter("ResetPasswordCode", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UpdateUser", useridParameter, kadiParameter, sifreParameter, mailParameter, olusumtarihParameter, aktifmiParameter, adminmiParameter, resimParameter, sozlesmeParameter, isimParameter, soyisimParameter, telefonParameter, cinsiyetidParameter, moderatormuParameter, resetPasswordCodeParameter);
        }
    }
}
