//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace alenen
{
    using System;
    using System.Collections.Generic;
    
    public partial class Begeni
    {
        public int begeniid { get; set; }
        public Nullable<int> userid { get; set; }
        public Nullable<int> yorumid { get; set; }
    
        public virtual User User { get; set; }
        public virtual Yorum Yorum { get; set; }
    }
}
