//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace alenen
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kategori
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Kategori()
        {
            this.Konulars = new HashSet<Konular>();
        }
    
        public int kategoriid { get; set; }
        public string kategoriad { get; set; }
        public string aciklama { get; set; }
        public Nullable<System.DateTime> olustarih { get; set; }
        public Nullable<int> olusturanid { get; set; }
        public string resim { get; set; }
        public Nullable<int> anakatid { get; set; }
    
        public virtual AnaKategori AnaKategori { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Konular> Konulars { get; set; }
    }
}
