//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace alenen
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public User()
        {
            this.Begenis = new HashSet<Begeni>();
            this.Konulars = new HashSet<Konular>();
            this.Yorums = new HashSet<Yorum>();
        }
    
        public int userid { get; set; }
        public string mail { get; set; }
        public string kadi { get; set; }
        public string sifre { get; set; }
        public Nullable<bool> aktifmi { get; set; }
        public Nullable<bool> adminmi { get; set; }
        public string resim { get; set; }
        public Nullable<bool> sozlesme { get; set; }
        public Nullable<System.DateTime> olusumtarih { get; set; }
        public string isim { get; set; }
        public string soyisim { get; set; }
        public string telefon { get; set; }
        public Nullable<int> cinsiyetid { get; set; }
        public Nullable<bool> moderatormu { get; set; }
        public string ResetPasswordCode { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Begeni> Begenis { get; set; }
        public virtual Cinsiyet Cinsiyet { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Konular> Konulars { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Yorum> Yorums { get; set; }
    }
}
