//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace alenen
{
    using System;
    using System.Collections.Generic;
    
    public partial class Yorum
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Yorum()
        {
            this.Begenis = new HashSet<Begeni>();
        }
    
        public int yorumid { get; set; }
        public string icerik { get; set; }
        public Nullable<bool> onay { get; set; }
        public string resim { get; set; }
        public Nullable<int> userid { get; set; }
        public Nullable<int> konuid { get; set; }
        public Nullable<System.DateTime> olustarih { get; set; }
        public string video { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Begeni> Begenis { get; set; }
        public virtual Konular Konular { get; set; }
        public virtual User User { get; set; }
    }
}
